Improve the release process docs
bloq/eslint-config-bloq pull request #52
Opened 2024-11-05 15:27 UTC by gabmontes

The docs are more complete and easier to follow now.

2024-11-05 15:34 UTC, maxivarela submitted a review, later dismissed

2024-11-05 15:37 UTC, gndelia approved these changes

2024-11-05 17:22 UTC, leanazulyoro requested changes

2024-11-05 17:22 UTC, leanazulyoro commented on README.md
> +After creating the a feature branch and committing the changes, add a commit to update the package version:
```suggestion
After creating a feature branch and committing the changes, add a commit to update the package version:
```

2024-11-06 17:24 UTC, gndelia approved these changes

2024-11-06 18:24 UTC, leanazulyoro approved these changes

2024-11-06 18:25 UTC, merged