Fix vitest config
bloq/eslint-config-bloq pull request #53
Opened 2024-11-07 13:52 UTC by gndelia

The Vitest configuration has 2 errors:

- By using the legacy configuration of Eslint, the rules need to be prepended with `@vitest/` instead of `vitest`. This wasn't in the docs, and if not using the appropriate prefix, it gives an error of missing definition of rule. (I created an issue in their repo to improve the docs about this https://github.com/vitest-dev/eslint-plugin-vitest/issues/566)

- The config was disabling some rules that did not belong to the `vitest` plugin, but were from `bloq/node`. Commonly, with `mocha`, we would use `bloq/node` before `bloq/mocha`, which causes those rules to be available. We tried to replicate that here, but as I am using `esm`, we can't use some of the rules from `bloq/node`. By not including it, these rules are not defined, throwing an error as well. The correct behavior should be that every package should only disable rules from the config it extends. That's why I am removing from the `vitest` config the following disabling of rules:

```
'no-unused-expressions'
'node/no-unpublished-require'
'prefer-arrow/prefer-arrow-functions'
```

As the vitest config did not work, I consider this a bug fix instead of a breaking change.

2024-11-07 16:03 UTC, gabmontes requested changes

2024-11-07 16:03 UTC, gabmontes commented on vitest.js
Let's sort the keys in `rules` so the checks do not throw a warning.

2024-11-07 16:07 UTC, gndelia commented on vitest.js
I did not even notice 😮‍💨  I thought I had checked the linter locally 🤔

2024-11-07 16:07 UTC, gndelia commented on vitest.js
fixed in [e53e062](https://github.com/bloq/eslint-config-bloq/pull/53/commits/e53e0620dd14a4834989b390ae9e0f3503306ef4)

2024-11-07 18:02 UTC, gabmontes approved these changes

2024-11-07 20:55 UTC, leanazulyoro approved these changes

2024-11-08 12:38 UTC, maxivarela approved these changes

2024-11-08 13:55 UTC, merged